"""CASCADE

Revision ID: 2298031230a8
Revises: a83c6a22453a
Create Date: 2024-01-12 09:27:09.903046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2298031230a8'
down_revision = 'a83c6a22453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('messages_sender_id_fkey', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###
