"""UserMixin

Revision ID: 9f23845ac1aa
Revises: f734752f6760
Create Date: 2024-01-01 16:41:44.055093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f23845ac1aa'
down_revision = 'f734752f6760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('users_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_name_key', ['name'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
