"""picture_filename not unique

Revision ID: f088ea4beb6f
Revises: 9f23845ac1aa
Create Date: 2024-01-01 23:37:36.967131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f088ea4beb6f'
down_revision = '9f23845ac1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_picture_filename_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_picture_filename_key', ['picture_filename'])

    # ### end Alembic commands ###
